version: "3.9"

services:

  webdav:
    image: ghcr.io/moerchel/docker-webdav:main
    container_name: webdav
    ports:
      - "8080:80"
    volumes:
      - ./data:/media/data
      - ./logs:/media/logs
    environment:
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
